name: Make Orb
description: Create a new pyorbs orb
branding:
  icon: target
  color: gray-dark

inputs:
  name:
    description: The name of the orb
    required: false
    default: magic
  requirements:
    description: The path to the requirements file
    required: false
    default: requirements.txt

runs:
  using: composite
  steps:
    - name: Create orb
      shell: bash
      run: |-
        pip install --upgrade pyorbs~=2.0
        orb --make ${{ inputs.name }} --requirements ${{ inputs.requirements }}
        orb --glow ${{ inputs.name }}
